apiVersion: v1
kind: Secret
metadata:
  name: documents-view-secrets
  labels:
    app: documents-view
    part-of: insure-pilot
    managed-by: kustomize
type: Opaque
# This is a base Secret template. Actual secret values should be provided by
# environment-specific overlays using secretGenerator in kustomization.yaml.
# Do not store actual secrets in this file.
data:
  app_key: ''        # Laravel application key
  db_username: ''    # Database username for Documents View
  db_password: ''    # Database password for Documents View
  redis_password: '' # Redis password for caching and queue processing
  adobe_sdk_key: ''  # Adobe Acrobat PDF Viewer SDK API key