apiVersion: v1
kind: Service
metadata:
  name: documents-view
  labels:
    app: documents-view
    component: web
    part-of: insure-pilot
    managed-by: kustomize
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: api
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: documents-view
    component: web
---
apiVersion: v1
kind: Service
metadata:
  name: documents-view-frontend
  labels:
    app: documents-view
    component: frontend
    part-of: insure-pilot
    managed-by: kustomize
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: documents-view
    component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: documents-view-backend
  labels:
    app: documents-view
    component: backend
    part-of: insure-pilot
    managed-by: kustomize
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/api/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: documents-view
    component: backend