{{- /* Generate Application Secrets */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "documents-view.fullname" . }}-app-secrets
  labels:
    {{- include "documents-view.labels" . | nindent 4 }}
type: Opaque
data:
  APP_KEY: {{ .Values.appSecrets.appKey | b64enc | quote }}
  SENDGRID_API_KEY: {{ .Values.appSecrets.sendgridApiKey | b64enc | quote }}
  ADOBE_PDF_API_KEY: {{ .Values.appSecrets.adobePdfApiKey | b64enc | quote }}
  ADOBE_PDF_CLIENT_ID: {{ .Values.appSecrets.adobePdfClientId | b64enc | quote }}
  LGTM_API_KEY: {{ .Values.appSecrets.lgtmApiKey | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.appSecrets.encryptionKey | b64enc | quote }}
---
{{- /* Generate Database Credentials Secret */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "documents-view.fullname" . }}-db-credentials
  labels:
    {{- include "documents-view.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.externalDatabase.enabled }}
  {{- if .Values.externalDatabase.existingSecret }}
  # Using existing secret for external database
  {{- else }}
  username: {{ .Values.externalDatabase.user | b64enc | quote }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- else }}
  username: {{ .Values.mariadb.auth.username | b64enc | quote }}
  password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  {{- end }}
---
{{- /* Generate Redis Credentials Secret */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "documents-view.fullname" . }}-redis-credentials
  labels:
    {{- include "documents-view.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.externalRedis.enabled }}
  {{- if .Values.externalRedis.existingSecret }}
  # Using existing secret for external Redis
  {{- else }}
  password: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
  {{- else }}
  password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}