auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: "30s"
  http_server_write_timeout: "30s"
  grpc_server_max_recv_msg_size: 4194304
  grpc_server_max_send_msg_size: 4194304

common:
  path_prefix: /data/loki
  storage:
    filesystem:
      chunks_directory: /data/loki/chunks
      rules_directory: /data/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: "0s"
  chunk_idle_period: "1h"
  chunk_retain_period: "30s"
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /data/loki/wal

schema_config:
  configs:
    - from: "2023-01-01"
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: "24h"
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks

compactor:
  working_directory: /data/loki/compactor
  shared_store: filesystem
  compaction_interval: "10m"
  retention_enabled: true
  retention_delete_delay: "2h"
  retention_delete_worker_count: 150

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: "168h"
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_global_streams_per_user: 10000
  max_query_length: "12h"
  max_query_parallelism: 32
  per_tenant_override_config: /etc/loki/tenant-limits.yaml
  per_tenant_override_period: "10s"
  retention_period: "90d"
  retention_period_overrides:
    documents-view-critical: "365d"
    documents-view-audit: "7y"

ruler:
  storage:
    type: local
    local:
      directory: /data/loki/rules
  rule_path: /data/loki/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
  evaluation_interval: "1m"

analytics:
  reporting_enabled: false

frontend:
  compress_responses: true
  log_queries_longer_than: "10s"
  max_outstanding_per_tenant: 2048

frontend_worker:
  frontend_address: 127.0.0.1:9096
  grpc_client_config:
    max_send_msg_size: 4194304

query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: "24h"

table_manager:
  retention_deletes_enabled: true
  retention_period: "90d"

distributor:
  ring:
    kvstore:
      store: inmemory

querier:
  query_timeout: "2m"
  max_concurrent: 20
  engine:
    timeout: "3m"
    max_look_back_period: "5m"

log_streams:
  - name: application
    description: General application logs from all components
    retention: "90d"
    labels:
      app: documents-view
      environment: ${ENVIRONMENT}
  - name: document_operations
    description: Logs specific to document viewing, editing, and processing operations
    retention: "90d"
    labels:
      app: documents-view
      component: document-operations
      environment: ${ENVIRONMENT}
  - name: audit
    description: Audit logs for compliance and security tracking
    retention: "7y"
    labels:
      app: documents-view
      component: audit
      environment: ${ENVIRONMENT}
  - name: security
    description: Security-related events and potential issues
    retention: "365d"
    labels:
      app: documents-view
      component: security
      environment: ${ENVIRONMENT}
  - name: performance
    description: Performance metrics and slow operations
    retention: "30d"
    labels:
      app: documents-view
      component: performance
      environment: ${ENVIRONMENT}

integration_points:
  - component: Promtail
    purpose: Collects logs from Kubernetes pods and files
    configuration: Configured to scrape logs from document-viewer pods and parse structured JSON logs
  - component: Grafana
    purpose: Visualizes logs in dashboards
    configuration: Uses Loki as a data source for log queries and visualizations
  - component: Tempo
    purpose: Correlates logs with traces
    configuration: Shares trace IDs with Loki for unified observability
  - component: Alertmanager
    purpose: Sends alerts based on log patterns
    configuration: Receives alerts from Loki's ruler component